name: Build Frida iOS (Minimal OK)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Clone
        run: |
          git clone --recurse-submodules https://github.com/frida/frida.git .
          git checkout 16.2.1
          git submodule update --init --recursive

      - name: Setup
        run: |
          brew install meson ninja pkg-config
          python3 -m venv venv
          source venv/bin/activate
          pip install meson ninja

      - name: Build arm64
        run: |
          set -e
          source venv/bin/activate

          cd subprojects/frida-core

          meson setup build \
            --cross-file=releng/ios/ios-arm64.txt \
            -Dserver=true

          meson compile -C build

      - name: Show Output
        run: |
          find subprojects/frida-core/build -name "frida-server"
